
import React from 'react';
import { Container, DitherGrid } from '../components/UI';

const Privacy: React.FC = () => {
  return (
    <div className="pt-32 min-h-screen bg-black text-white font-sans selection:bg-white selection:text-black">
      <DitherGrid className="opacity-10 fixed inset-0 z-0" />
      
      <Container className="relative z-10">
        <article className="max-w-3xl mx-auto pb-24">
            
            {/* Header */}
            <header className="mb-12">
                <h1 className="text-5xl md:text-7xl font-display font-bold mb-4 tracking-tighter">Privacy Policy</h1>
                <p className="font-mono text-xs text-coral uppercase tracking-widest">Effective Date: November 14, 2025</p>
            </header>
            
            {/* Main Content */}
            <div className="prose prose-invert prose-lg">
                <p className="lead text-xl text-gray-300">
                    At Asymmetric.al, operating under Global Fellowship Inc., we view data stewardship as a sacred trust. This Privacy Policy details how we collect, use, and protect your information when you use our Platform ("Mission Control") and related services.
                </p>

                <h3>1. Information We Collect</h3>
                <p>
                    We collect different types of information for various purposes to provide and improve our Service to you.
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, Address, State, Province, ZIP/Postal code, City.</li>
                    <li><strong>Usage Data:</strong> We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</li>
                    <li><strong>Transaction Data:</strong> For donors and organizations, we process transaction details necessary to complete donations. Note that full credit card numbers are never stored on our servers; they are processed directly by our payment provider, Stripe.</li>
                </ul>

                <h3>2. Use of Data</h3>
                <p>Asymmetric.al uses the collected data for various purposes:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>To provide and maintain the Service.</li>
                    <li>To notify you about changes to our Service.</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so.</li>
                    <li>To provide customer care and support.</li>
                    <li>To provide analysis or valuable information so that we can improve the Service.</li>
                    <li>To monitor the usage of the Service.</li>
                    <li>To detect, prevent and address technical issues.</li>
                </ul>

                <h3>3. Data Sovereignty & Stewardship</h3>
                <p>
                    We operate under a philosophy of tenant sovereignty. Data generated by a ministry organization (Tenants) on our platform belongs to that organization. We act as data processors, not owners. We do not sell, rent, or trade your data to third parties for marketing purposes.
                </p>

                <h3>4. Service Providers (Third Parties)</h3>
                <p>
                    We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
                <p><strong>Key Processors include:</strong></p>
                <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li><strong>Stripe:</strong> Payment processing. Their Privacy Policy can be viewed at https://stripe.com/us/privacy.</li>
                    <li><strong>SendGrid:</strong> Email delivery services.</li>
                    <li><strong>Vercel/AWS:</strong> Infrastructure and hosting.</li>
                </ul>

                <h3>5. Security of Data</h3>
                <p>
                    The security of your data is important to us. We utilize AES-256 encryption at rest and TLS 1.3 encryption in transit. However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>

                <h3>6. Data Retention</h3>
                <p>
                    We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>

                <h3>7. Your Data Rights (GDPR/CCPA)</h3>
                <p>
                    Depending on your location, you may have rights regarding your personal data, including the right to access, correct, or delete your data. To exercise these rights, please contact us at info@asymmetric.al.
                </p>

                <h3>8. Changes to This Privacy Policy</h3>
                <p>
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
                </p>
            </div>

            {/* Footer */}
            <footer className="mt-12 pt-12 border-t border-white/10">
                <p className="text-sm text-gray-500">
                    <strong>Contact Us</strong><br/>
                    If you have any questions about this Privacy Policy, please contact us:<br/>
                    <a 
                        href="mailto:info@asymmetric.al" 
                        className="text-white hover:text-primary transition-colors inline-block mt-1"
                    >
                        info@asymmetric.al
                    </a>
                </p>
            </footer>
        </article>
      </Container>
    </div>
  );
};

export default Privacy;
